### PR TITLE
Updating to Python 3.9 + CODEOWNERS

### PR DESCRIPTION
**Pull request by marcglobality**
Update Python to 3.9 + small required changes to do so

This also updates the CODEOWNERS to AI CODEOWNERS

### CODE REVIEW

**Comment by tomaszpietruszka-globality** [comment]
Is the "not requiring to ignore pytest_sagemaker plugin" part related to the Python version, or the editable install?

**Comment by marcglobality** [comment]
> Is the "not requiring to ignore pytest_sagemaker plugin" part related to the Python version, or the editable install?

Just not to let your comment hanging, yeah you were right so now it's just the minimal changes

**Review by tomaszpietruszka-globality — APPROVED** [review]
LGTM!

**Review by salmanmashayekh — APPROVED** [review]
LGTM

**Pull request merged**
