### PR TITLE
add wandb project name setting

### PR DESCRIPTION
**Pull request by uri-miron-globality**
Add the ability to set the wandb project name.

### CODE REVIEW

**Review by marcglobality — COMMENTED** [review]
Could you link a PR (from SOC I suppose) where this is used and working?

**Comment by uri-miron-globality** [comment]
> Could you link a PR (from SOC I suppose) where this is used and working?

@marcglobality, I don't have a PR that uses it, it's mainly to for experiments (to not use the same `wandb` project as production).

**Comment by marcglobality** [comment]
As discussed offline, here's an example on how to use it:
```
from fancy_classifier.app_hooks.train.app import create_app
from microcosm.loaders import load_from_dict

CONFIG = dict(
    weights_and_biases=dict(project_name="fancy-classifier", enable=True),
)

graph = create_app(
    debug=True,
    testing=False,
    extra_loader=load_from_dict(CONFIG),
)
```

**Review by marcglobality — APPROVED** [review]

**Review by salmanmashayekh — APPROVED** [review]
LGTM

**Pull request merged**
